default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contacts_development

test:
  <<: *default
  database: contacts_test

production:
  <<: *default
  database: contacts_production
  username: contacts
  password: <%= ENV['CONTACTS_DATABASE_PASSWORD'] %>
